name: Linux with Sysdeps

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Install build Dependencies
        run: |
          sudo apt update
          sudo apt install -y libjsoncpp-dev fakeroot libarchive-tools python3-apt zstd gettext
          curl "https://cdn.anotherfoxguy.com/makedeb/install-makedeb.sh" | sudo bash
          git clone https://git.anotherfoxguy.com/AnotherFoxGuy/makedeb-pkgs.git
          cd makedeb-pkgs/angelscript 
          makedeb -is
          cd ..
          cd socketw
          makedeb -is          

      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        run: make -j4
